#!/usr/bin/env python3
"""Independently check graph scans and measure retained macro subgroup coverage.

Every catalog-word/shape pair is compared between dense graph traversal and
compiled independent bond obstructions, including exact closure. GAP measures
the group generated by the bounded checked shortlist; complete native loops
are then included to certify its index and retain missing native witnesses.
This does not compile or benchmark an end-to-end staged solution.
"""

import argparse
import json
from pathlib import Path
from time import perf_counter

import bce_v2 as c
from bce_v2.gap_backend import analyze_generators
import numpy as np

from familiar_algorithm_catalog import build
from probe_algorithm_obstructions import BONDS, compile_word_obstruction
from probe_familiar_algorithm_transport import transitions
from profile_notebook_graph import notebook_bandage


def bond_array(graph):
    labels = np.asarray([shape.labels for shape in graph.shapes], dtype=np.uint8)
    result = np.zeros(len(graph), dtype=np.uint64)
    for index, (first, second) in enumerate(BONDS):
        result |= (labels[:, first] == labels[:, second]).astype(np.uint64) << np.uint64(index)
    return result


def measure(record, compiled):
    name = record["puzzle"]
    graph = c.explore(notebook_bandage(name))
    actions = transitions(graph)
    bits = bond_array(graph)
    starts = np.arange(len(graph), dtype=np.int32)
    start = perf_counter()
    for algorithm, (forbidden, destinations) in zip(record["algorithms"], compiled):
        ends = starts.copy()
        for move in algorithm["word"].split():
            ends = actions[move][ends]
        graph_legal, graph_closed = ends != len(graph), ends == starts
        mask_legal = (bits & np.uint64(forbidden)) == 0
        final_bits = np.zeros(len(graph), dtype=np.uint64)
        for source, destination in destinations.items():
            final_bits |= ((bits >> np.uint64(source)) & np.uint64(1)) * np.uint64(destination)
        mask_closed = mask_legal & (final_bits == bits)
        assert np.array_equal(graph_legal, mask_legal), (name, algorithm["id"], "legality")
        assert np.array_equal(graph_closed, mask_closed), (name, algorithm["id"], "closure")
        assert int(graph_legal.sum()) == algorithm["legal_shapes"]
        assert int(graph_closed.sum()) == algorithm["closed_shapes"]
    comparisons_seconds = perf_counter() - start

    root = c.Shape(notebook_bandage(name))
    macros = []
    for row in record["checked_candidates"]:
        replay = c.State(root).apply(row["conjugate"])
        assert replay.shape == root, (name, row["algorithm_id"], "root closure")
        macros.append(tuple(replay.sticker_permutation))
    macros = list(dict.fromkeys(macros))
    start = perf_counter()
    macro_group = analyze_generators(macros, timeout=30)
    macro_group_seconds = perf_counter() - start
    macro_basis = [macros[index] for index in macro_group.generator_indices]
    start = perf_counter()
    loops = c.isotropy_loops(graph)
    originals = loops.generators
    complete = analyze_generators(macro_basis + [g.permutation for g in originals],
                                  prune=False, timeout=30)
    # Macro actions are legal root loops, so adjoining all native loops gives
    # exactly the complete isotropy group. GAP tests membership of every input.
    assert complete.group_order % macro_group.group_order == 0
    augmentations = []
    for index in complete.generator_indices:
        if index >= len(macro_basis):
            generator = originals[index - len(macro_basis)]
            replay = c.State(root).apply(generator.turn_sequence)
            assert replay.shape == root and replay.sticker_permutation == generator.permutation
            augmentations.append(dict(id=generator.id, word=generator.turn_sequence,
                                      htm=generator.htm_length))
    full_group_seconds = perf_counter() - start
    result = dict(puzzle=name, graph_catalog_pairs=len(graph) * len(compiled),
                  legality_mismatches=0, closure_mismatches=0,
                  comparison_seconds=comparisons_seconds,
                  checked_shortlist_group_order=macro_group.group_order,
                  checked_shortlist_basis_size=len(macro_basis),
                  complete_isotropy_order=complete.group_order,
                  checked_shortlist_index=complete.group_order // macro_group.group_order,
                  all_originals_membership_checked=len(originals),
                  native_augmentations=augmentations,
                  gap_version=complete.gap_version,
                  macro_group_seconds=macro_group_seconds, full_group_seconds=full_group_seconds)
    print(f"{name}: {result['graph_catalog_pairs']} graph/mask pairs match; "
          f"shortlist index {result['checked_shortlist_index']}; "
          f"{len(augmentations)} native augmentations", flush=True)
    return result


def main():
    base = Path(__file__).resolve().parent.parent / "research-results"
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=base / "familiar-algorithm-transport.json")
    parser.add_argument("--output", type=Path, default=base / "familiar-algorithm-transport-check.json")
    args = parser.parse_args()
    report = json.loads(args.input.read_text())
    catalog = build()
    start = perf_counter()
    compiled = [compile_word_obstruction(row["word"]) for row in catalog["variants"]]
    compile_seconds = perf_counter() - start
    for record in report["puzzles"]:
        assert [r["word"] for r in record["algorithms"]] == [r["word"] for r in catalog["variants"]]
    result = dict(scope="exact discovery verification and bounded-shortlist group coverage",
                  compiled_words=len(compiled), compilation_seconds=compile_seconds,
                  puzzles=[measure(record, compiled) for record in report["puzzles"]])
    result["total_graph_catalog_pairs"] = sum(r["graph_catalog_pairs"] for r in result["puzzles"])
    args.output.write_text(json.dumps(result, indent=2) + "\n")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
